---
- name: add apt repository
  apt_repository:
    repo: ppa:ubuntu-mozilla-daily/firefox-aurora
    state: present
  become: yes

- name: install
  apt:
    name:
      - firefox
      - firefox-locale-en
      - firefox-locale-fr
    state: latest
    update_cache: yes
  become: yes
  notify:
    - apt autoremove
