---
- name: add apt repository
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
  become: yes

- name: install
  apt:
    name: fish
    state: latest
    update_cache: yes
  become: yes
  notify:
    - apt autoremove
