---
- name: install bash
  apt:
    name: bash
    state: latest
    update_cache: yes
  become: yes
  notify:
    - apt autoremove

- name: copy dotfiles
  copy:
    src: "dotfile/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .bash_aliases
    - .bash_prompt
    - .bashrc
    - .face
    - .node-completion

- name: copy config
  copy:
    src: config/fontconfig
    dest: ~/.config
