---
- name: install
  apt:
    deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb"
  vars:
    slack_version: "4.0.2"
  become: yes
  notify:
    - apt autoremove
