---
- name: add apt key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes

- name: add apt repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
  become: yes

- name: install chrome
  apt:
    name: google-chrome-stable
    state: latest
    update_cache: yes
  become: yes
  notify:
    - apt autoremove
