---
- name: add repository
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
  become: yes

- name: install
  apt:
    name: ansible
    state: latest
    update_cache: yes
  become: yes
  notify:
    - apt autoremove
