---
- name: add apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: add apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: yes

- name: install
  apt:
    name: docker
    state: latest
    update_cache: yes
  become: yes
  notify:
    - apt autoremove
