---
- name: add apt repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present
  become: yes

- name: ensure other versions are not installed
  apt:
    name:
      - php7.4
      - php7.2
      - php7.1
      - php7.0
      - php5.6
    state: absent
    purge: yes
  become: yes
  notify:
    - apt autoremove

- name: install
  apt:
    name:
      - php7.3
      - php7.3-*
      - php-redis
    state: latest
    update_cache: yes
  become: yes
  notify:
    - apt autoremove
