---
- name: install
  apt:
    name:
      - vim
      - vim-gtk
    state: latest
    update_cache: yes
  become: yes
  notify:
    - apt autoremove

- name: create .vim directory and .vimrc file
  copy:
    src: "{{ item }}"
    dest: "~/"
  with_items:
    - .vimrc
    - .vim

- name: create pathogen dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.vim/autoload
    - ~/.vim/bundle

- name: pull pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim

- name: pull vim plugins
  git:
    repo: "{{ item.repository }}"
    dest: "~/.vim/bundle/{{ item.name }}"
    clone: yes
    update: yes
  with_items:
    - repository: https://github.com/Lokaltog/vim-powerline.git
      name: powerline
    - repository: https://github.com/Shougo/neocomplete.vim.git
      name: neocomplete
    - repository: https://github.com/SirVer/ultisnips.git
      name: ultisnips
    - repository: https://github.com/Yggdroot/indentLine.git
      name: indentLine
    - repository: https://github.com/arnaud-lb/vim-php-namespace.git
      name: php-namespace
    - repository: https://github.com/editorconfig/editorconfig-vim.git
      name: editorconfig
    - repository: https://github.com/ekalinin/Dockerfile.vim.git
      name: Dockerfile
    - repository: https://github.com/elzr/vim-json.git
      name: json
    - repository: https://github.com/evidens/vim-twig.git
      name: twig
    - repository: https://github.com/godlygeek/tabular.git
      name: tabular
    - repository: https://github.com/jparise/vim-graphql.git
      name: graphql
    - repository: https://github.com/junegunn/goyo.vim.git
      name: goyo
    - repository: https://github.com/junegunn/limelight.vim.git
      name: limelight
    - repository: https://github.com/kien/ctrlp.vim.git
      name: ctrlp
    - repository: https://github.com/majutsushi/tagbar.git
      name: tagbag
    - repository: https://github.com/posva/vim-vue.git
      name: vue
    - repository: https://github.com/sheerun/vim-polyglot.git
      name: polyglot
    - repository: https://github.com/sjbach/lusty.git
      name: lusty
    - repository: https://github.com/stephpy/vim-yaml.git
      name: yaml
    - repository: https://github.com/terryma/vim-multiple-cursors.git
      name: multiple-cursor
    - repository: https://github.com/tpope/vim-dispatch.git
      name: dispatch
    - repository: https://github.com/tpope/vim-eunuch.git
      name: eunuch
    - repository: https://github.com/tpope/vim-fugitive.git
      name: figitive
    - repository: https://github.com/tpope/vim-ragtag.git
      name: ragtag
    - repository: https://github.com/veloce/vim-behat.git
      name: behat
    - repository: https://github.com/w0rp/ale.git
      name: ale
    - repository: https://github.com/phpactor/phpactor.git
      name: phpactor
    - repository: https://github.com/prabirshrestha/async.vim.git
      name: async
    - repository: https://github.com/autozimu/LanguageClient-neovim.git
      name: lsp-client

- name: install phpactor
  composer:
    working_dir: ~/.vim/bundle/phpactor
    command: install
    prefer_dist: yes

- name: install language client
  command: ~/.vim/bundle/lsp-client/install.sh
  args:
    chdir: ~/.vim/bundle/lsp-client

- name: install yaml language server
  npm:
    global: yes
    name: yaml-language-server
    state: latest
  become: true

- name: install php language server
  npm:
    global: yes
    name: intelephense
    state: latest
  become: true
