---
- name: purge apt package
  apt:
    name: ruby-full
    state: absent
  become: yes
  notify:
    - apt autoremove

- name: install
  snap:
    name: ruby
    classic: yes
    state: present
  become: yes

- name: copy dotfiles
  copy:
    src: "{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - .gemrc
